FROM ghcr.io/rspamd/rspamd-docker:3.10

ENV SERVICE=rspamd

LABEL org.opencontainers.image.source=https://github.com/Neomediatech/${SERVICE} \
      org.opencontainers.package.name=rspamd

USER root

ARG BIN_SOURCE=https://github.com/Neomediatech/assets/raw/refs/heads/main/bin
ADD --chmod=777 ${BIN_SOURCE}/gosu \
                ${BIN_SOURCE}/wget \
                /usr/local/bin/

SHELL ["/bin/bash", "-c"]

RUN echo 'pidfile = false;' > /etc/rspamd/override.d/options.inc && \
    mkdir -p /srv/scripts && \
    wget -O /srv/scripts/logrotate.sh https://raw.githubusercontent.com/Neomediatech/assets/main/scripts/logrotate.sh && \
    chmod +x /srv/scripts/logrotate.sh && \
    chown -R 11333:11333 /etc/rspamd

COPY conf/ /etc/rspamd
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=20 CMD rspamadm control stat |grep uptime|head -1 || ( echo "no uptime, no party\!" && exit 1 )

ENTRYPOINT ["/entrypoint.sh"]

#USER 11333:11333
CMD [ "/usr/bin/rspamd", "-f" ]
#CMD [ "/usr/bin/rspamd", "-f", "-u", "_rspamd", "-g", "_rspamd" ]

